analytics/urls.py
from django.urls import path
from .views import AnalyticsView, click_analyse, total_links_json_view
from django.contrib.auth.decorators import login_required

app_name = 'analytics'

urlpatterns = [
    path('', login_required(AnalyticsView.as_view()), name='analytics-view'),
    path('analyse/<int:shortcode>/', click_analyse, name='click-data-analyse'),
    path('analytics/total-links/', total_links_json_view, name='total_links_json'),
]

linkinbio/urls.py
from django.urls import path

from .views import (
        LinkInBioListView,
        LinkInBioDetailView,
        ShortcodeClassListView,
        CreateShortcodeView,
        CreateLinkView,
        LinkInBioLinksListView,
        UpdateLinksOrderView,
        get_social_media_platforms,
        SaveUrlSocialView,
        LinksDetaileJsonView,
        UpdateShortcodeLinkInBioView,
        updateSwichtLinkinbioAtive,
        LinkinbiolinkDeleteView,
        LinkinbioDetaileJsonView,
        UpdateFormLinkInBioSingel,
        ImageSaveAdjustmentView,
        ProfileImageDetailView,
        TexteCreateAdjustmentView,
        TexteDeatileAdjustmentView,
        UrlSocialProfilesViewList,
        UrlSocialProfilesUpdateView,
        UrlSocialProfilesDeleteView,
        LinkInBioViewEditScreen,
        CustomSettingsView,
        CustomSettingsUpdateView,
        SocialMediaProfilesOrderSaveView,
        DeleteImageAdjustmentView,
        BackgroundImageJson
    )


app_name = 'linkinbio'

urlpatterns = [
    path('', LinkInBioListView.as_view(), name='linkinbio_view_list'),
    path('shortcode/', ShortcodeClassListView.as_view(), name='shortcode_class_list'),
    path('create_shortcode/', CreateShortcodeView.as_view(), name='create_shortcode'),
    path('create_link/', CreateLinkView.as_view(), name='create_link'),
    path('update_links_order/', UpdateLinksOrderView.as_view(), name='update_links_order'),
    path('get_social_media_platforms/', get_social_media_platforms, name='get_social_media_platforms'),
    path('save_social_profiles/', SaveUrlSocialView.as_view(), name='save_url_social'),
    path('social_media_profiles_order_save/', SocialMediaProfilesOrderSaveView.as_view(), name='social_media_profiles_order_save'),
    path('update_shorcode_linkinbio/<int:pk>/', UpdateShortcodeLinkInBioView.as_view(), name='update_shortcode_linkinbio'),
    path('detail/<int:pk>/', LinkInBioDetailView.as_view(), name='linkinbio_detail'),
    path('links/<int:linkinbio_id>/', LinkInBioLinksListView.as_view(), name='linkinbio_links_list'),
    path('link_detaile/<pk>/', LinksDetaileJsonView.as_view(), name='link_in_bio_link'),
    path('swicht_update/<pk>/', updateSwichtLinkinbioAtive.as_view(), name='swicht_update'),
    path('linkinbio_jeson/<int:pk>/', LinkinbioDetaileJsonView.as_view(), name='linkinbio_json'),
    path('linkinbio_update_json/<int:pk>/', UpdateFormLinkInBioSingel.as_view(), name='linkinbio_update_json'),
    path('linkinbio_delete_json_new/<int:pk>/', LinkinbiolinkDeleteView.as_view(), name='linkinbio_delete_json'),
    path('adjustment_profile_image_json/<int:pk>/', ImageSaveAdjustmentView.as_view(), name='adjustment_profile_image_json'),
    path('adjustment_profile_image_delete_json/<int:pk>/', DeleteImageAdjustmentView.as_view(), name='adjustment_profile_image_delete_json'),
    path('adjustment_dataile_profile_image_json/<int:pk>/', ProfileImageDetailView.as_view(), name='adjustment_dataile_profile_image_json'),
    path('adjustment_create_text_json/<int:pk>/', TexteCreateAdjustmentView.as_view(), name='adjustment_create_text_json'),
    path('adjustment_detaile_text_json/<int:pk>/', TexteDeatileAdjustmentView.as_view(), name='adjustment_detaile_text_json'),
    path('url_social_profiles_view_list/<int:pk>/', UrlSocialProfilesViewList.as_view(), name='url_social_profiles_view_list'),
    path('url_social_profiles_view_update/<int:pk>/', UrlSocialProfilesUpdateView.as_view(), name='url_social_profiles_view_update'),
    path('url_social_profiles_view_delete/', UrlSocialProfilesDeleteView.as_view(), name='url_social_profiles_view_delete'),
    path('linkinbio_edit_screen/<int:pk>/', LinkInBioViewEditScreen.as_view(), name='linkinbio_edit_screen'),
    path('custom_settings_view/<int:pk>/', CustomSettingsView.as_view(), name='custom_settings_view'), 
    path('custom_settings_update_view/<int:pk>/', CustomSettingsUpdateView.as_view(), name='custom_settings_update_view'), 
    path('background_image_json/<int:pk>/', BackgroundImageJson.as_view(), name='background_image_json'), 
]

products/urls.py
from django.urls import path
from .views import ProductListView, cancel, success, create_checkout_session, create_checkout_session_subscription
app_name = 'products'

urlpatterns = [
    path('', ProductListView.as_view(), name='product_list'),
    path('success/', success, name='success-page'),
    path('cancel/', cancel, name='cancel-page'),
    path('create-checkout-session/', create_checkout_session, name='create_checkout_session'),
    path('create-checkout-session-subscription/', create_checkout_session_subscription, name='create_checkout_session_subscription'),
    # path('stripe-webhook/', stripe_webhook, name='stripe_webhook'),
]

# stripe listen --forward-to http://127.0.0.1:8000/stripe-webhook/

recommendation/urls.py
from django.urls import path

from .views import RecommendationSend, RecommendationView

app_name = 'recommendation'

urlpatterns = [
    path('', RecommendationSend.as_view(), name='recommendation_send'),
    path('list/', RecommendationView.as_view(), name='recommendation_list'),
]

src/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

from django.conf import settings
from django.conf.urls.static import static

from accounts.views import URLRedirectView

from django.views.i18n import set_language as django_set_language

from products.views import stripe_webhook
from linkinbio.views import LinkInBioDeatilePage
from django.views.i18n import JavaScriptCatalog

urlpatterns = [
    path('admin/', admin.site.urls),
    path('stripe-webhook/', stripe_webhook, name='stripe_webhook'),
    path('m/<int:pk>/', LinkInBioDeatilePage.as_view(), name='detail_page'),
]

urlpatterns += i18n_patterns(
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    path('shortcode/', include('shortcode.urls')),
    path('analytics/', include('analytics.urls')),
    path('webclicktracker/', include('webclicktracker.urls')),
    path('linkinbio/', include('linkinbio.urls')),
    path('geotargeting/', include('geotargeting.urls')),
    path('products/', include('products.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('domain/', include('domain.urls')),
    path('recommendation/', include('recommendation.urls')),
    path('', include('accounts.urls')),
    url(r'^(?P<shortcode>[\w-]+)/$', URLRedirectView.as_view(), name='scode'), 
)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

analytics/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from accounts.models import CustomUser
from shortcode.models import ShortcodeClass

from django.db.models import Sum

class ClickEventManager(models.Manager):
    def create_event(self, shortInstance):
        if isinstance(shortInstance, ShortcodeClass):
            obj, created = self.get_or_create(short_url=shortInstance)
            obj.count += 1
            obj.save()
            return obj.count
        return None

class ClickEvent(models.Model):
    short_url   = models.OneToOneField(ShortcodeClass, on_delete=models.CASCADE)
    count       = models.IntegerField(default=0)
    updated     = models.DateTimeField(auto_now=True) 
    timestamp   = models.DateTimeField(auto_now_add=True)

    objects = ClickEventManager()

    def __str__(self):
        return "{i}".format(i=self.count)
    
    def get_short_url(self):
        return self.short_url.shortcode if self.short_url else ""
    
    
    @staticmethod
    def get_total_clicks_for_user(user):
        user_shortcodes = ShortcodeClass.objects.filter(url_creator=user, url_archivate=False)
        total_clicks = ClickEvent.objects.filter(short_url__in=user_shortcodes).aggregate(total=Sum('count'))['total']
        return total_clicks or 0
    
    
class DailyClick(models.Model):
    short_url = models.ForeignKey(ShortcodeClass, on_delete=models.CASCADE, related_name='daily_clicks')
    timestamp = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"Click on {self.short_url.shortcode} at {self.timestamp}"
    

# IPGeolocation
class IPGeolocation(models.Model):
    shortcode = models.ForeignKey(ShortcodeClass, on_delete=models.CASCADE, related_name='geolocations')
    ip_address = models.GenericIPAddressField(blank=True, null=True)
    country = models.CharField(max_length=100, blank=True, null=True)
    region = models.CharField(max_length=100, blank=True, null=True)
    city = models.CharField(max_length=100, blank=True, null=True)
    latitude = models.FloatField(blank=True, null=True)
    longitude = models.FloatField(blank=True, null=True)
    os = models.CharField(max_length=100, blank=True, null=True)
    device = models.CharField(max_length=100, blank=True, null=True)
    browser = models.CharField(max_length=100, blank=True, null=True)
    timestamp   = models.DateTimeField(auto_now_add=True)
    referrer = models.CharField(max_length=255, default="Unknown Referrer")

    def __str__(self):
        return f'IPGeolocation for Shortcode: {self.shortcode.shortcode}'
    



class ClickData(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    website_title = models.CharField(max_length=255)
    website_url = models.URLField()
    referrer = models.CharField(max_length=255)
    ip_address = models.GenericIPAddressField()
    os = models.CharField(max_length=255)
    device = models.CharField(max_length=255)
    browser = models.CharField(max_length=255)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} - {self.website_title} - {self.ip_address} - {self.timestamp}"

analytics/views.py
from django.views.generic.base import View
from django.shortcuts import render
from datetime import timedelta, date, datetime
from collections import Counter
from django.db.models import Sum

from django.db.models import Count
from django.db.models.functions import TruncDate
from django.shortcuts import get_object_or_404
from django.http import JsonResponse
from django.views import View
from .models import ClickEvent, DailyClick, IPGeolocation, ClickEvent
from shortcode.models import ShortcodeClass

from recommendation.models import Recommendation
from accounts.models import CustomUser

'''
@ToDo
    - 1.    Automatisches Versenden von Analyseberichten.
    - 2.    Intelligente Vorschläge für optimale Veröffentlichung Zeitpunkte
    - 3.    Websiten beuscher Zeitraum auf 24 Studen wan in wlecher zeit sind die meisten besucher auf der Website
    - 4.    Logo Tauschen
'''


# Create your views here.
class AnalyticsView(View):
    def get(self, request, *args, **kwargs):
        
        if request.user.recommended == 'recommended':
            
            recommended_user = Recommendation.objects.filter(referred_to_email=request.user).first()
            
            if recommended_user.status_change == False:
                recommended_user.status_change = True
                recommended_user.save()
                
            user = CustomUser.objects.get(pk=recommended_user.referred_by.id)
            user.free_user = False
            user.save()
    
        else:
            pass
        return render(request, "analytics.html")


def click_analyse(request, shortcode):

        obj = ShortcodeClass.objects.get(pk=shortcode)
        
        daily_clicks = obj.daily_clicks.all() 
        
        # Landdaten für Klicks sammeln
        country_clicks = {}
        for click in daily_clicks:
            ip_geolocation = IPGeolocation.objects.filter(shortcode=click.short_url).first()
            if ip_geolocation:
                country = ip_geolocation.country
                if country in country_clicks:
                    country_clicks[country] += 1
                else:
                    country_clicks[country] = 1
                  
        country_labels = list(country_clicks.keys())
        country_values = list(country_clicks.values())  
                    
        # # Erstellungsdatum
        created_at_datetime = obj.created_at
        creation_date = created_at_datetime.strftime('%Y-%m-%d')

        # # # Klicks in den gewünschten Zeiträumen
        today = date.today()
        thirty_days_ago = today - timedelta(days=31)
        ninety_days_ago = today - timedelta(days=90)
        one_twenty_days_ago = today - timedelta(days=120)
        one_year_ago = today - timedelta(days=365)
        
        # Prüfe, ob der Link mindestens 30 - 120 Tage alt ist
        if obj.created_at.date() <= thirty_days_ago:
            clicks_30_days = ClickEvent.objects.filter(short_url=obj, timestamp__gte=thirty_days_ago).count()
        else:
            clicks_30_days = 0
        
        if obj.created_at.date() <= ninety_days_ago:
            clicks_90_days = ClickEvent.objects.filter(short_url=obj, timestamp__gte=ninety_days_ago).count()
        else:
            clicks_90_days = 0
        
        if obj.created_at.date() <= one_twenty_days_ago:
            clicks_120_days = ClickEvent.objects.filter(short_url=obj, timestamp__gte=one_twenty_days_ago).count()
        else:
            clicks_120_days = 0
            
        if obj.created_at.date() <= one_year_ago:
            clicks_365_days = ClickEvent.objects.filter(short_url=obj, timestamp__gte=one_year_ago).count()
        else:
            clicks_365_days = 0
            
        # Landdaten für Klicks sammeln
        country_clicks = Counter()
        for click in daily_clicks:
            ip_geolocation = IPGeolocation.objects.filter(shortcode=click.short_url).first()
            if ip_geolocation:
                country = ip_geolocation.country
                country_clicks[country] += 1

        # Die Top-N-Länder ermitteln
        top_countries = country_clicks.most_common(10)

        
        # # # Datum der letzten Änderung
        update_at_datetime = obj.updated_at
        last_modification_date = update_at_datetime.strftime('%Y-%m-%d')

        # # # Weiterleitungen
        daily_clicks = obj.daily_clicks.all()
        redirections_counter = Counter(click.short_url.url_destination for click in daily_clicks)

        # Browserdaten sammeln und zählen
        browser_data = IPGeolocation.objects.filter(shortcode=obj).values('browser').annotate(count=Count('browser')).order_by('-count')[:10]
        top_browsers = [(browser['browser'], browser['count']) for browser in browser_data]
        
        # Betriebssystemdaten sammeln und zählen
        os_data = IPGeolocation.objects.filter(shortcode=obj).values('os').annotate(count=Count('os')).order_by('-count')[:10]
        top_os = [(os['os'], os['count']) for os in os_data]
        
        # Top-Referrer sammeln und zählen
        top_referrers_data = IPGeolocation.objects.filter(shortcode=obj).values('referrer').annotate(count=Count('referrer')).order_by('-count')[:10]
        top_referrers = [(referrer['referrer'], referrer['count']) for referrer in top_referrers_data]
        
        # Daten für ApexCharts
        data = {
            'creation_date': creation_date,
            'clicks_30_days': clicks_30_days,
            'clicks_90_days': clicks_90_days,
            'clicks_120_days': clicks_120_days,
            'clicks_365_days': clicks_365_days,
            'last_modification_date': last_modification_date,
            'redirections_counter': redirections_counter,
            'country_labels': country_labels,
            'country_values': country_values,
            'top_countries': top_countries,
            'top_browsers': top_browsers,
            'top_os': top_os,
            'top_referrers': top_referrers,
            'url': obj.get_short_url,
            'url_destination': obj.url_destination
            #Füge hier die Daten für die ApexCharts hinzu
        }
    

        return JsonResponse(data)


def total_links_json_view(request):
    total_links = ShortcodeClass.objects.filter(url_creator=request.user, url_archivate=False).count()
    total_archiv = ShortcodeClass.objects.filter(url_creator=request.user, url_archivate=True).count()
    
    total_clicks = ClickEvent.get_total_clicks_for_user(request.user)
    
    item = {
        'total_links': total_links,
        'total_archiv': total_archiv,
        'total_clicks': total_clicks,
        }

    return JsonResponse(item)

analytics/templates/analytics.html
{% extends "basic.html" %}
{% load static %}
{% load i18n %}

{% block body %}
<link rel="stylesheet" type="text/css" href="{% static '/assets/css/accounts.css' %}">
<link rel="stylesheet" type="text/css" href="{% static '/assets/css/analytics.css' %}">

    <!--Sidebar-->
    {% include "includes/sidebar.html" %}

    <div class="container-fluid p-0 bg-body">
        
        <!--Navbar-->
        {% include "includes/navbar.html" %}

        <!--Main-->
        <div id="body-main" class="main">

            <div class="container-fluid mt-5 px-4">
                <div class="row">
                    <div class="col-12">
                        <div class="d-flex flex-row align-items-center">
                            <h3 class="p-1" style="margin-top: 10px;">{% trans "Dashboard" %}</h3>
                        </div>
                    </div>
                </div>
            </div>

            <div class="container-fluid mt-5">

                <div class="row px-2">
                    <div class="car-12 col-6">
                        <div class="card border-0 shadow-sm">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-12 col-md-5">
                                        <img src="{% static 'images/influencer.webp' %}" class="img-fluid">
                                    </div>
                                    <div class="col-12 col-md-7">
                                        <h5>{% trans "Every click tells a story" %}</h5>
                                        <p>{% trans "Make it short" %}</p>
                                        <a href="{% url 'shortcode:shortcode_list_view' %}" type="button" class="btn btn-primary btn-sm">{% trans "Go to Links" %}</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="car-12 col-6">
                        <div class="card border-0 shadow-sm">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-12 col-md-5">
                                        <img src="{% static 'images/agenturen.webp' %}" class="img-fluid">
                                    </div>
                                    <div class="col-12 col-md-7">
                                        <h5>{% trans "Organize your links." %}</h5>
                                        <p>{% trans "Make a page" %}</p>
                                        <a href="{% url 'linkinbio:linkinbio_view_list' %}" type="button" class="btn btn-primary btn-sm">{% trans "Go to page" %}</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>


                <div class="row px-2 mt-3">
                    <div class="col-12">
                        <div class="card border-0 shadow-sm">
                            <div class="card-body">
                                <div class="row p-2">
                                    <div class="col-12 p-2">
                                        <span id="openModelInfo" style="right: 30px; top:30px; color:#0c3ebb; cursor:pointer;" class="position-absolute"><i class="fa-solid fa-circle-info"></i></span>
                                        <form id="recommendedForm">
                                            <div class="form-group">
                                              <label for="exampleInputEmail1" class="mb-1">Email address</label>
                                              <input type="email" class="form-control" id="UserRecommend" aria-describedby="emailHelp" placeholder="Who would you like to recommend to us?">
                                              <small id="emailHelp" class="form-text text-muted">Recommend us and you will receive all functions free of charge for 1 year.</small>
                                            </div>
                                            <button type="submit" class="btn btn-primary mt-3">Recommend us</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row px-2 mt-3">
                    <div class="col-12">
                        <div class="card border-0 shadow-sm">
                            <div class="card-body">
                              <div class="row p-2">
                                <div class="col-12 col-md-5">
                                    <img class="img-fluid" src="{% static 'images/Geo-Targeting.webp' %}">
                                </div>
                                <div class="col-12 col-md-7 p-5">
                                    <h5>{% trans "Gain comprehensive insights: Consolidate your click and scan data into one dashboard" %}</h5>
                                    <p class="mt-3">{% trans "Get a holistic overview: Centralize your click and scan analytics in one dashboard." %}</p>
                                    <a href="{% url 'products:product_list' %}" type="button" class="btn btn-primary btn-sm mt-auto">{% trans "Go to page" %}</a>
                                </div>
                              </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>




    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Information about your recommendations</h5>
            </div>
            <div class="modal-body">
            <table id="RecommendedInfo" style="width: 100%;">
                <thead>
                  <tr>
                    <th>e-mail address</th>
                    <th>Confirmation</th>
                  </tr>
                </thead>
                <tbody>
                  <!-- Hier werden die Zeilen dynamisch hinzugefügt -->
                </tbody>
            </table>
            

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" id="CloseInfo">Close</button>
            </div>
        </div>
        </div>
    </div>




    <input type="hidden" id="RecommendationSend" value="{% url 'recommendation:recommendation_send' %}">
    <input type="hidden" id="RecommendationView" value="{% url 'recommendation:recommendation_list' %}">

{% endblock body %}

{% block javasript %}
<script type="module" src="{% static '/js/recommended.bundle.js' %}" defer></script>
{% endblock %}