linkinbio/urls.py
from django.urls import path

from .views import (
        LinkInBioListView,
        LinkInBioDetailView,
        ShortcodeClassListView,
        CreateShortcodeView,
        CreateLinkView,
        LinkInBioLinksListView,
        UpdateLinksOrderView,
        get_social_media_platforms,
        SaveUrlSocialView,
        LinksDetaileJsonView,
        UpdateShortcodeLinkInBioView,
        updateSwichtLinkinbioAtive,
        LinkinbiolinkDeleteView,
        LinkinbioDetaileJsonView,
        UpdateFormLinkInBioSingel,
        ImageSaveAdjustmentView,
        ProfileImageDetailView,
        TexteCreateAdjustmentView,
        TexteDeatileAdjustmentView,
        UrlSocialProfilesViewList,
        UrlSocialProfilesUpdateView,
        UrlSocialProfilesDeleteView,
        LinkInBioViewEditScreen,
        CustomSettingsView,
        CustomSettingsUpdateView,
        SocialMediaProfilesOrderSaveView,
        DeleteImageAdjustmentView,
        BackgroundImageJson
    )


app_name = 'linkinbio'

urlpatterns = [
    path('', LinkInBioListView.as_view(), name='linkinbio_view_list'),
    path('shortcode/', ShortcodeClassListView.as_view(), name='shortcode_class_list'),
    path('create_shortcode/', CreateShortcodeView.as_view(), name='create_shortcode'),
    path('create_link/', CreateLinkView.as_view(), name='create_link'),
    path('update_links_order/', UpdateLinksOrderView.as_view(), name='update_links_order'),
    path('get_social_media_platforms/', get_social_media_platforms, name='get_social_media_platforms'),
    path('save_social_profiles/', SaveUrlSocialView.as_view(), name='save_url_social'),
    path('social_media_profiles_order_save/', SocialMediaProfilesOrderSaveView.as_view(), name='social_media_profiles_order_save'),
    path('update_shorcode_linkinbio/<int:pk>/', UpdateShortcodeLinkInBioView.as_view(), name='update_shortcode_linkinbio'),
    path('detail/<int:pk>/', LinkInBioDetailView.as_view(), name='linkinbio_detail'),
    path('links/<int:linkinbio_id>/', LinkInBioLinksListView.as_view(), name='linkinbio_links_list'),
    path('link_detaile/<pk>/', LinksDetaileJsonView.as_view(), name='link_in_bio_link'),
    path('swicht_update/<pk>/', updateSwichtLinkinbioAtive.as_view(), name='swicht_update'),
    path('linkinbio_jeson/<int:pk>/', LinkinbioDetaileJsonView.as_view(), name='linkinbio_json'),
    path('linkinbio_update_json/<int:pk>/', UpdateFormLinkInBioSingel.as_view(), name='linkinbio_update_json'),
    path('linkinbio_delete_json_new/<int:pk>/', LinkinbiolinkDeleteView.as_view(), name='linkinbio_delete_json'),
    path('adjustment_profile_image_json/<int:pk>/', ImageSaveAdjustmentView.as_view(), name='adjustment_profile_image_json'),
    path('adjustment_profile_image_delete_json/<int:pk>/', DeleteImageAdjustmentView.as_view(), name='adjustment_profile_image_delete_json'),
    path('adjustment_dataile_profile_image_json/<int:pk>/', ProfileImageDetailView.as_view(), name='adjustment_dataile_profile_image_json'),
    path('adjustment_create_text_json/<int:pk>/', TexteCreateAdjustmentView.as_view(), name='adjustment_create_text_json'),
    path('adjustment_detaile_text_json/<int:pk>/', TexteDeatileAdjustmentView.as_view(), name='adjustment_detaile_text_json'),
    path('url_social_profiles_view_list/<int:pk>/', UrlSocialProfilesViewList.as_view(), name='url_social_profiles_view_list'),
    path('url_social_profiles_view_update/<int:pk>/', UrlSocialProfilesUpdateView.as_view(), name='url_social_profiles_view_update'),
    path('url_social_profiles_view_delete/', UrlSocialProfilesDeleteView.as_view(), name='url_social_profiles_view_delete'),
    path('linkinbio_edit_screen/<int:pk>/', LinkInBioViewEditScreen.as_view(), name='linkinbio_edit_screen'),
    path('custom_settings_view/<int:pk>/', CustomSettingsView.as_view(), name='custom_settings_view'), 
    path('custom_settings_update_view/<int:pk>/', CustomSettingsUpdateView.as_view(), name='custom_settings_update_view'), 
    path('background_image_json/<int:pk>/', BackgroundImageJson.as_view(), name='background_image_json'), 
]

src/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

from django.conf import settings
from django.conf.urls.static import static

from accounts.views import URLRedirectView

from django.views.i18n import set_language as django_set_language

from products.views import stripe_webhook
from linkinbio.views import LinkInBioDeatilePage
from django.views.i18n import JavaScriptCatalog

urlpatterns = [
    path('admin/', admin.site.urls),
    path('stripe-webhook/', stripe_webhook, name='stripe_webhook'),
    path('m/<int:pk>/', LinkInBioDeatilePage.as_view(), name='detail_page'),
]

urlpatterns += i18n_patterns(
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    path('shortcode/', include('shortcode.urls')),
    path('analytics/', include('analytics.urls')),
    path('webclicktracker/', include('webclicktracker.urls')),
    path('linkinbio/', include('linkinbio.urls')),
    path('geotargeting/', include('geotargeting.urls')),
    path('products/', include('products.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('domain/', include('domain.urls')),
    path('recommendation/', include('recommendation.urls')),
    path('', include('accounts.urls')),
    url(r'^(?P<shortcode>[\w-]+)/$', URLRedirectView.as_view(), name='scode'), 
)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

linkinbio/forms.py
from django import forms
from .models import LinkInBio
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Row, Column, HTML, Hidden

from django.utils.translation import gettext_lazy as _

class LinkInBioDashboardForm(forms.ModelForm):
    title = forms.CharField(label="Titel", widget=forms.TextInput(attrs={'placeholder': _('Titel')}))
    #description = forms.CharField(label="Description", widget=forms.TextInput(attrs={'placeholder': _('Description')}))
    
    submit_text = _("Save")
    
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None) 
        super(LinkInBioDashboardForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.layout = Layout(
            Row(
                Column('title', css_class='form-group col-12 my-2'),
                css_class='row',
            ),
            # Row(
            #     Column('description', css_class='form-group col-12 my-2'),
            #     css_class='row'
            # ),
            HTML('<div class="character-count"></div>'),
            Hidden('user', '{{ admin }}'),
            HTML('<input id="saveBtn" class="btn btn-primary mt-3" type="submit" value="{}">'.format(self.submit_text)),
            HTML('<input id="updateBtnJson" class="btn btn-primary mt-3 d-none" value="{}">'.format(self.submit_text)),
        )
        
    class Meta:
        model = LinkInBio
        fields = ['title']

linkinbio/views.py
import json
import os
import requests
from django.urls import reverse
from bs4 import BeautifulSoup
from django.db import models
from django.db import transaction
from django.shortcuts import get_object_or_404
from django.http import HttpRequest

from django.views.decorators.http import require_POST
from django.utils.translation import gettext_lazy as _

from django.shortcuts import render, redirect
from django.http import JsonResponse, HttpResponseBadRequest, HttpResponseServerError
from django.http import HttpResponse
from django.views import View
from django.http import Http404
from django.contrib.auth.mixins import LoginRequiredMixin
from shortcode.models import ShortcodeClass, Tag
from .models import LinkInBio, LinkInBioLink, CustomSettings, SocialMediaPlatform, UrlSocialProfiles
from .forms import LinkInBioDashboardForm



# View Edit Screen
class LinkInBioViewEditScreen(LoginRequiredMixin, View):
    def get(self, request, pk):
            try:
                linkinbio = LinkInBio.objects.get(pk=pk)
                
                # Alle UrlSocialProfiles für diese LinkInBio-Seite abrufen
                url_social_profiles = UrlSocialProfiles.objects.filter(link_in_bio=linkinbio).order_by('order')
                
                # Alle LinkInBioLink-Einträge für diese LinkInBio-Seite abrufen
                link_in_bio_links = LinkInBioLink.objects.filter(link_in_bio=linkinbio, is_aktiv=True).order_by('order')

                
                # Daten für die Antwort erstellen
                data = {
                    'url_social_profiles': [
                        {
                            'platform': profile.social_media_platform.name,
                            'icon': profile.social_media_platform.icon_svg,
                            'url_social': profile.url_social
                        }
                        for profile in url_social_profiles
                    ],
                    'link_in_bio_links': [
                        {   'image': link.image.url if link.image else None,
                            'link_text': link.shortcode.button_label,
                            'url': link.shortcode.shortcode
                        }
                        for link in link_in_bio_links
                    ],
                    'title': linkinbio.title,
                    'description': linkinbio.description
                }
                
                return JsonResponse({'links': data})
            except LinkInBio.DoesNotExist:
                return JsonResponse({'error': _('LinkInBio not found.')}, status=404)
            

# Delete Social Media
class UrlSocialProfilesDeleteView(LoginRequiredMixin, View):
    def post(self, request):
        try:
            url_social_id = request.POST.get('url_social_id')  # ID des zu löschenden URL-Social-Profils
            
            # Versuchen Sie, das zu löschende URL-Social-Profil zu finden und zu löschen
            url_social_profile = UrlSocialProfiles.objects.get(id=url_social_id)
            url_social_profile.delete()
            
            return JsonResponse({'social_media_delete': _('URL deleted successfully.')})
        except UrlSocialProfiles.DoesNotExist:
            return JsonResponse({'error': 'UrlSocialProfiles nicht gefunden.'}, status=404)


# Update Url Social Media
class UrlSocialProfilesUpdateView(View):
    def post(self, request, pk):
        try:
            url_social_id = request.POST.get('url_social_id')
            new_url = request.POST.get('url_social') 

            url_social_profile = UrlSocialProfiles.objects.get(id=url_social_id)
            
            url_social_profile.url_social = new_url
            url_social_profile.save()
            
            return JsonResponse({'message': _('URL updated successfully.')})
        except UrlSocialProfiles.DoesNotExist:
            return JsonResponse({'error': 'UrlSocialProfiles nicht gefunden.'}, status=404)
        

# Select View Sozial Media
class UrlSocialProfilesViewList(LoginRequiredMixin, View):
    def get(self, request, pk):
        try:
            link_in_bio = LinkInBio.objects.get(id=pk)
            social_media_profiles = UrlSocialProfiles.objects.filter(link_in_bio=link_in_bio).order_by('order')
            
            # Eine Liste erstellen, um alle Sozialen Medien-Links und deren Status zu speichern
            social_media_data = []
            
            for profile in social_media_profiles:
                social_media_data.append({
                    'platform': profile.social_media_platform.name,
                    'url': profile.url_social,
                    'id': profile.pk,
                    'order': profile.order
                })
            
            return JsonResponse({'social_media': social_media_data, 'message': _('Saved successfully.')})
        except LinkInBio.DoesNotExist:
            return JsonResponse({'error': 'LinkInBio not found'}, status=404)


# Wir vielleicht nicht mehr gebraucht!
class SocialMediaProfilesOrderSaveView(LoginRequiredMixin, View):
    def post(self, request):
        try:            
            sorted_links = request.POST.getlist('sorted_links[]')

            for index, link_id in enumerate(sorted_links):
                link = UrlSocialProfiles.objects.get(id=link_id)
                link.order = index + 1
                link.save()
            return JsonResponse({'social_media_profiles': sorted_links})

        except LinkInBio.DoesNotExist:
            return JsonResponse({'error': 'LinkInBio not found'}, status=404)



# Save Url Social Profiles
class SaveUrlSocialView(LoginRequiredMixin, View):
    def post(self, request):
        try:
            url_social = request.POST.get('url_social')
            link_in_bio_id = request.POST.get('link_in_bio_id')
            social_media_platform = request.POST.get('social_media_platform')

            platform_instance = SocialMediaPlatform.objects.get(name=social_media_platform)
            # Prüfen, ob ein LinkInBio-Eintrag mit der angegebenen ID existiert
            link_in_bio = LinkInBio.objects.get(id=link_in_bio_id)

            # URL in das Modell speichern
            url_social_profile = UrlSocialProfiles(url_social=url_social, link_in_bio=link_in_bio, social_media_platform=platform_instance)
            url_social_profile.save()

            response_data = {'success': True, 'message': _('URL saved successfully.')}
            return JsonResponse(response_data)

        except LinkInBio.DoesNotExist:
            response_data = {'success': False, 'message': _('LinkInBio-Seite nicht gefunden.')}
            return JsonResponse(response_data, status=404)


# Social Media Platform Auswahl mit exclude
def get_social_media_platforms(request):
    link_in_bio_page_id = request.GET.get('link_in_bio_page_id')

    # Erhalte eine Liste der Plattformen, die nicht mit der LinkInBio-Seite verknüpft sind
    platforms = SocialMediaPlatform.objects.exclude(urlsocialprofiles__link_in_bio_id=link_in_bio_page_id).values('id', 'name')

    data = {'platforms': list(platforms)}
    return JsonResponse(data)


# Ajax-Anfrage zum Speichern der Reihenfolge
class UpdateLinksOrderView(LoginRequiredMixin, View):
    def post(self, request):
        try:
            sorted_links = request.POST.getlist('sorted_links[]')

            for index, link_id in enumerate(sorted_links):
                link = LinkInBioLink.objects.get(id=link_id)
                link.order = index + 1
                link.save()

            response_data = {'success': True, 'message': _('Order saved successfully.')}
            return JsonResponse(response_data)
        except Exception as e:
            response_data = {'success': False, 'message': str(e)}
            return JsonResponse(response_data, status=400)


# Link liste Datile LinkInBio
class LinkInBioLinksListView(LoginRequiredMixin, View):
    def get(self, request, linkinbio_id):
        try:
            # Holen Sie sich die LinkInBio-Seite anhand ihrer ID
            linkinbio = LinkInBio.objects.get(id=linkinbio_id)

            # Holen Sie sich alle Links in der gewünschten Reihenfolge
            links = LinkInBioLink.objects.filter(link_in_bio=linkinbio).order_by('order')

            links_data = [{
                    'id': link.id,
                    'button_label': link.shortcode.button_label,
                    'url_destination': link.shortcode.url_destination,
                    'shortcode_url': link.shortcode.shortcode,
                    'order': link.order,
                    'url_titel': link.shortcode.url_titel,
                    'link_in_bio_page': link.link_in_bio.id,
                    'shortcode_id': link.shortcode.id,
                    'is_aktiv': link.is_aktiv,
                }
                for link in links
            ]

            return JsonResponse({'links': links_data})

        except LinkInBio.DoesNotExist:
            return JsonResponse({'error': 'LinkInBio-Seite nicht gefunden'}, status=404)



class updateSwichtLinkinbioAtive(LoginRequiredMixin, View):
    def post(self, request, pk):
        try:

            linkinbio = LinkInBioLink.objects.get(id=pk)

            linkinbio.is_aktiv = not linkinbio.is_aktiv

            linkinbio.save()

            response_data = {'success': True, 'message': _('Link updated successfully.')}
            return JsonResponse(response_data)
            
            
        except json.JSONDecodeError:
            response_data = {'success': False, 'message': 'Ungültiges JSON-Format.'}
            return JsonResponse(response_data, status=400)

'''
@Create Link
Die vorhandene Shortcode wird ausgewählt und mit dem LinkInBio verknüpft.
'''
class CreateLinkView(LoginRequiredMixin, View):
    @transaction.atomic
    def post(self, request):
        try:
            shortcode_id = request.POST.get('shortcode_id')
            linkinbio_page_id = request.POST.get('linkinbio_page_id')

linkinbio/templates/includes/form_linkinbio.html
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}

<aside id="aside-form" class="crate-form p-3">

    <div class="card p-2 border-0">
        <div class="card-header bg-white border-0">
            <button id="closeForm" type="button" class="btn btn-secondary btn-sm">{% trans "Close" %}</button>
        </div>
    </div>

    <div class="card">
        <div class="card-body">
            <div class="card p-2">
                <form method="post">
                    {% crispy link_in_bio_form %}  
                    <input type="hidden" id="linkinbioUpdateId">
                </form>
            </div>
        </div>
    </div>

</aside>

linkinbio/templates/includes/links.html
{% load static %}
{% load i18n %}

<div class="row" id="linkinbio-links">
    <div class="col-12">
        <button type="button" id="createOpenCloseForm" class="btn btn-primary my-3">Add a link</button> 

        <div id="createlinkinbio" class="card shadow-sm border-0 d-none mb-3">
            <div class="card-body">

                <div class="d-flex flex-row align-items-center">
                    <input class="form-check-input p-2 m-2" type="checkbox" id="createShorcode" value="option1" checked>
                    <label class="form-check-label" for="createShorcode">Create a new Llinkb link</label>
                
                    <input class="form-check-input p-2 m-2" type="checkbox" id="createSearch" value="option1">
                    <label class="form-check-label" for="createSearch">Select an existing Llinkb link</label>
                </div>

                <!-- Formular 1 (Erstellen) -->
                <form id="form-create-shorcode" style="display: block;" action="{% url 'linkinbio:create_shortcode' %}" method="POST">
                    <div class="mb-3">
                        <input type="text" class="form-control mt-3 mb-3" id="buttonLabelSubmit" placeholder="Button label">
                        <input type="text" class="form-control mt-3 mb-3" id="linkUrlSubmit" placeholder="Create a new Llinkb link">
                        <input type="hidden" id="linkInBioPageID" value="{{link_in_bio_instance.id}}">

                        <input class="form-control mt-3 mb-3" type="file" id="formFile">
                        
                        <button type="submit" id="buttonCrateShortcode" class="btn btn-primary btn-sm disabled">Create</button>
                    </div>
                </form>

                

                <!-- Formular 2 (Auswählen) -->
                <form id="form-create-link-select" class="d-none" action="{% url 'linkinbio:create_link' %}" method="POST">
                    <div class="mb-3">
                        <input type="text" class="form-control mt-3 mb-3" id="buttonLabelSelcetSubmit" placeholder="Button label">
                        <input type="text" class="form-control mt-3 mb-3" id="selectShortcode" placeholder="Select an existing Llinkb link">
                        <ul id="search-results"></ul>
                        
                        <input class="form-control mt-3 mb-3" type="file" id="formFile2">

                        <input type="hidden" id="linkinbio_page_id" value="{{link_in_bio_instance.id}}">
                        <input type="hidden" id="shortcode_id" value="">

                        <button type="submit" id="buttonCrateSelectShortcode" class="btn btn-primary btn-sm disabled">Create</button>
                    </div>
                </form>

            </div>
        </div>

        <div id="card-container-form">
            <div class="row d-none" id="linkInBioCardAddForm">
                <div class="col-12">
                    <div class="mb-3">
                        <div id="createlinkinbio" class="card shadow-sm border-0 mb-3">
                            <div class="card-body">
    
                            <!--Form Shortcode Update-->
                            <form id="form-create-shorcode-update">
                                <div class="mb-3">
                                    <label for="buttonLabelLabel" class="form-label">Button Label</label>
                                    <input type="text" class="form-control mb-3" id="buttonLabel" placeholder="Button label">
                                    <label for="urlDestinationUpdateLabel" class="form-label">Url</label>
                                    <input type="text" class="form-control mb-3 inputSearchform" id="urlDestinationUpdate">
                                    <ul id="search-results-update"></ul>
                                    <input type="hidden" id="shortcodeId" value="">
                                    <input type="hidden" id="linkInBioPageIdValue" value="">
                                    <button type="submit" class="btn btn-primary btn-sm updateformlink">Update</button>
                                    <!-- <button type="submit" id="cancel" class="btn btn-secondary btn-sm cencleButton">Abbrechen</button> -->
                                </div>
                            </form>
                
                            </div>
                        </div>                    
                
                    </div>
                </div>
            </div>
        </div>

    </div>

    <div class="col-12">
        <img class="loader-image mx-auto d-block d-none" src="{% static '/gif/load-38_256.gif' %}">
        <!--Value Links-->
        <div id="card-container"></div>
        <input type="hidden" id="updateUrl" value="{% url 'linkinbio:update_shortcode_linkinbio' 0 %}">
        <input type="hidden" id="viewUrlLinks" value="{% url 'linkinbio:link_in_bio_link' 0 %}">
        <input type="hidden" id="valueUrlSort" value="{% url 'linkinbio:update_links_order' %}">
        <input type="hidden" id="valueUrlShotcodeAutocomplete" value="{% url 'linkinbio:shortcode_class_list' %}">
        <input type="hidden" id="swichtupdate" value="{% url 'linkinbio:swicht_update' 0 %}">
        <input type="hidden" id="deleteLinkinLink" value="{% url 'linkinbio:linkinbio_delete_json' 0 %}">
    </div>

    
</div>

linkinbio/templates/includes/performance.html
<div class="card border-0 linkinbio-radius-bottom">
    <div class="card-body">
        ...
    </div>
</div>