shortcode/urls.py
from django.urls import path, include

urlpatterns = [
    path('short/', include('shortcode.views.short_urls')),
    path('tags/', include('shortcode.views.tags_urls')),
    path('archive/', include('shortcode.views.archive_urls')),
]


# from shortcode.views.views_main import (
#     post_crate_view, 
#     load_shortcode_data_view, 
#     GetFaviconView, 
#     post_detaile_data_view, 
#     archive_post, update_post, 
#     ShortcodeArchiveListView, 
#     GetArchivedShortcodesView,
#     export_shortcodes_to_excel,
#     filter_and_search_shortcodes,
#     get_all_tags,
#     CreateTagView,
#     TagDeleteView,
#     TagListView,
#     edit_tag,
#     shortcode_view,
#     DeleteShortcodesView,
#     unarchive_selected_shortcodes)

# from shortcode.views.views_targeting import (
#     toggle_limitation_active_status, 
#     get_limitation_active_status,
#     get_deatile_android_targeting,
#     get_detaile_ios_targeting,
#     get_detaile_geo_targeting,
#     toggle_geo_targeting_active_satus,
#     toggle_android_targeting_active_status,
#     toggle_ios_targeting_active_status,
#     limitationTargetingUpdateView,
#     GeoTargetingUpdateView,
#     AndroidTargetingUpdateView,
#     IosTargetingUpdateView)




# urlpatterns = [
#     path('create/', post_crate_view, name='dashboard-create'),
#     path('update/<pk>/', update_post, name='dashboard-update'),
#     path('update/<pk>/view/', post_detaile_data_view, name='dashboard-update-view'),
#     path('archive/', ShortcodeArchiveListView.as_view(), name='archive-view'),
#     path('delete/', DeleteShortcodesView.as_view(), name='delete_shortcodes'),
#     path('archive/list/', GetArchivedShortcodesView.as_view(), name='archive-list-view'),
#     path('archive/update/', archive_post, name='dashboard-archive'),
#     path('unarchive/', unarchive_selected_shortcodes, name='unarchive_selected_shortcodes'),
#     path('ajax/export-shortcodes/', export_shortcodes_to_excel, name='ajax_export_shortcodes'),
#     path('list/', shortcode_view, name='shortcode_list_view'),
#     path('json-list/', load_shortcode_data_view, name='load_shortcode_data'),
#     path('get_favicon/', GetFaviconView.as_view(), name='get_favicon'),
#     path('serach/', filter_and_search_shortcodes, name='serach'),
#     path('tags/', get_all_tags, name='tags'),
#     path('tags-create/', CreateTagView.as_view(), name='tags-create'),
#     path('tags-list/', TagListView.as_view(), name='tag-list'),
#     path('tags-edit/<int:tag_id>/', edit_tag, name='tag-edit'),
#     path('tags-delete/<int:tag_id>/', TagDeleteView.as_view(), name='tag-delete'),
#     path('toggle_limitation_active_status/<int:pk>/', toggle_limitation_active_status, name='toggle_limitation_active_status'),
#     path('get_limitation_active_status/<int:pk>/', get_limitation_active_status, name='get_limitation_active_status'),
#     path('get_detaile_geo_targeting/<int:pk>/', get_detaile_geo_targeting, name='get_detaile_geo_targeting'),
#     path('get_detaile_ios_targeting/<int:pk>/', get_detaile_ios_targeting, name='get_detaile_ios_targeting'),
#     path('get_deatile_android_targeting/<int:pk>/', get_deatile_android_targeting, name='get_deatile_android_targeting'),
#     path('toggle_geo_targeting_active_satus/<int:pk>/', toggle_geo_targeting_active_satus, name='toggle_geo_targeting_active_satus'),
#     path('toggle_android_targeting_active_status/<int:pk>/', toggle_android_targeting_active_status, name='toggle_android_targeting_active_status'),
#     path('toggle_ios_targeting_active_status/<int:pk>/', toggle_ios_targeting_active_status, name='toggle_ios_targeting_active_status'),
#     path('update_limitation_targeting/<int:pk>/', limitationTargetingUpdateView.as_view(), name='update_geo_targeting'),
#     path('update_geo_targeting/<int:pk>/', GeoTargetingUpdateView.as_view(), name='update_geo_targeting'),
#     path('update_android_targeting/<int:pk>/', AndroidTargetingUpdateView.as_view(), name='update_android_targeting'),
#     path('update_ios_targeting/<int:pk>/', IosTargetingUpdateView.as_view(), name='update_ios_targeting'),
# ]

src/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

from django.conf import settings
from django.conf.urls.static import static

from accounts.views import URLRedirectView

from django.views.i18n import set_language as django_set_language

from products.views import stripe_webhook
from linkinbio.views import LinkInBioDeatilePage
from django.views.i18n import JavaScriptCatalog

urlpatterns = [
    path('admin/', admin.site.urls),
    path('stripe-webhook/', stripe_webhook, name='stripe_webhook'),
    path('m/<int:pk>/', LinkInBioDeatilePage.as_view(), name='detail_page'),
]

urlpatterns += i18n_patterns(
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    path('shortcode/', include('shortcode.urls')),
    path('analytics/', include('analytics.urls')),
    path('webclicktracker/', include('webclicktracker.urls')),
    path('linkinbio/', include('linkinbio.urls')),
    path('geotargeting/', include('geotargeting.urls')),
    path('products/', include('products.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('domain/', include('domain.urls')),
    path('recommendation/', include('recommendation.urls')),
    path('', include('accounts.urls')),
    url(r'^(?P<shortcode>[\w-]+)/$', URLRedirectView.as_view(), name='scode'), 
)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

shortcode/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from accounts.models import CustomUser
from geotargeting.models import GeoThemplate
from django_hosts.resolvers import reverse

from .utils import create_shortcode

SHORTCODE_MAX = getattr(settings, "SHORTCODE_MAX", 15)


class Tag(models.Model):
    name = models.CharField(max_length=50, unique=False)
    user = models.ForeignKey(CustomUser,on_delete=models.CASCADE,)

    def __str__(self):
        return self.name


class ShortcodeClass(models.Model):
    url_destination     = models.CharField(max_length=520, blank=False)
    url_titel           = models.CharField(max_length=125, blank=True)
    url_source          = models.CharField(max_length=525, blank=True)
    url_medium          = models.CharField(max_length=525, blank=True)
    url_campaign        = models.CharField(max_length=525, blank=True)
    url_term            = models.CharField(max_length=525, blank=True)
    url_content         = models.CharField(max_length=525, blank=True)
    url_creator         = models.ForeignKey(CustomUser,on_delete=models.CASCADE,)
    url_create_date     = models.DateTimeField(default=timezone.now)
    url_archivate       = models.BooleanField(default=False)
    url_active          = models.BooleanField(default=True)
    favicon_path        = models.CharField(max_length=255, blank=True, null=True)
    created_at          = models.DateTimeField(default=timezone.now)
    updated_at          = models.DateTimeField(default=timezone.now)
    tags                = models.ManyToManyField(Tag, related_name='shortcodes')
    
    #Button LinkInBio
    button_label        = models.CharField(max_length=520, blank=True, null=True) 
    shortcode           = models.CharField(max_length=SHORTCODE_MAX, unique=True, blank=True)
    
    # LinkInBio Page
    linkinbiopage        = models.ForeignKey('linkinbio.LinkInBio',on_delete=models.CASCADE, blank=True, null=True)

    
    # Begrenzung von URLs
    limitation_active = models.BooleanField(default=False)
    count = models.IntegerField(default=0)
    start_date = models.DateTimeField(null=True, blank=True)
    end_date = models.DateTimeField(null=True, blank=True)
    alternative_url = models.URLField(max_length=200, blank=True, null=True)

    # Geo-Targeting
    geo_targeting_on_off = models.BooleanField(default=False)
    link_geo = models.CharField(max_length=320, blank=True, null=True)
    template_geo = models.ManyToManyField(GeoThemplate, related_name='geothemplate', blank=True)
    
    # Android-Targeting
    android_on_off = models.BooleanField(default=False)
    android = models.CharField(max_length=320, blank=True, null=True)
    
    # iOS-Targeting
    ios_on_off = models.BooleanField(default=False)
    ios = models.CharField(max_length=320, blank=True, null=True)
    
    
    def __str__(self):
        return self.url_titel
    
    def save(self, *args, **kwargs):
        if not self.pk:
            self.created_at = timezone.now()
        self.updated_at = timezone.now()
        super().save(*args, **kwargs)
        
    def save(self, *args, **kwargs):
        if not self.shortcode or self.shortcode == "":
                self.shortcode = create_shortcode(self)

        if not self.url_destination.startswith("http"):
            self.url_destination = "http://" + self.url_destination

        super(ShortcodeClass, self).save(*args, **kwargs)

    
    @property
    def get_full_url(self):
        url_parts = []

        if self.url_destination:
            url_parts.append(self.url_destination)

        if self.url_medium and self.url_source:
            url_basic = '?utm_medium=' + self.url_medium + '&utm_source=' + self.url_source
            url_parts.append(url_basic)

        if self.url_campaign:
            url_parts.append('&utm_campaign=' + self.url_campaign)

        if self.url_term:
            url_parts.append('&utm_term=' + self.url_term)

        if self.url_content:
            url_parts.append('&utm_content=' + self.url_content)

        full_url = ''.join(url_parts)
        return full_url
    
    
    @property
    def archivate_count(self):
        return self.url_archivate.count()
    
    
    @property
    def get_short_url(self):
        url_path = reverse("scode", kwargs={'shortcode': self.shortcode}, host='www', scheme='http')
        url_path = url_path.replace('/en/', '/').replace('/de/', '/')
        return url_path
    

shortcode/views/archive_urls.py
from django.urls import path

from shortcode.views.archivi_views import (
        ShortcodeAcivieren,
        ArchivListLiftView,
        ShortcodeUnarchived
    )

app_name = 'archive'

urlpatterns = [
    path('', ArchivListLiftView.as_view(), name='achivie_list'),
    path('unarchived/', ShortcodeUnarchived.as_view(), name='shortcode_unarchived'),
    path('achivie/<int:pk>/', ShortcodeAcivieren.as_view(), name='shortcode_achivie'),
]

shortcode/views/archivi_views.py
import requests
from django.views import View
from django.shortcuts import render
from django.http.response import JsonResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.translation import gettext_lazy as _
from shortcode.models import ShortcodeClass, Tag

#Archivieren & Aufheben
class ShortcodeAcivieren(View, LoginRequiredMixin):
    def get(self, request, pk):
        try:
            shortcode = ShortcodeClass.objects.get(pk=pk)
            print(shortcode)
            if shortcode.url_archivate == False:
                shortcode.url_archivate = True
                shortcode.save()
            else:
                shortcode.url_archivate = False
                shortcode.save()
            return JsonResponse({'success': _('Shortcodes have been successfully archived.')})  
        except ShortcodeClass.DoesNotExist:
            return JsonResponse({'error': _('Your link has been successfully created.')})


# Entarchivieren
class ShortcodeUnarchived(View):
    def post(self, request):
        if request.is_ajax():
            selected_shortcodes = request.POST.getlist('selected_shortcodes[]')
            print(selected_shortcodes)
            for shortcode_id in selected_shortcodes:
                try:
                    shortcode = ShortcodeClass.objects.get(pk=shortcode_id, url_creator=request.user)
                    shortcode.url_archivate = False
                    shortcode.save()
                except ShortcodeClass.DoesNotExist:
                    pass

                response_data = {'message': _('The selected shortcodes have been successfully unarchived.')}
                return JsonResponse(response_data)




# Archive List % Shorcode löschen
class ArchivListLiftView(View):
    def get(self, request):
        template_name = 'archive.html'
        
        if 'application/json' in request.META.get('HTTP_ACCEPT', ''):
            if request.is_ajax():
                archived_shortcodes = ShortcodeClass.objects.filter(url_creator=request.user, url_archivate=True)
                
                shortcode_data = [{
                    'id': shortcode.id, 
                    'url_titel': shortcode.url_titel, 
                    'url_destination':shortcode.url_destination, 
                    'url_create_date':shortcode.url_create_date.strftime('%d %b %Y'),
                    } for shortcode in archived_shortcodes]

                return JsonResponse({'archived_shortcodes': shortcode_data})
        else:
            return render(request, template_name)
        
    def post(self, request):
        if request.is_ajax():
            shortcode_ids = request.POST.getlist('shortcode_ids[]')
            try:
                # Lösche die ausgewählten Shortcodes aus der Datenbank
                ShortcodeClass.objects.filter(pk__in=shortcode_ids).delete()
                message = _('Shortcodes have been successfully deleted.')
            except Exception as e:
                message_trans = _('Error deleting shortcodes: ')
                message = message_trans + str(e)

            return JsonResponse({'message': message})
        else:
            return JsonResponse({'error': 'Ungültige Anfrage'})

shortcode/views/short_urls.py
from django.urls import path

from shortcode.views.short_views import (
        ShortcodeListeCreateView,
        ShortcodeSingelUpdateView,
        CheckingUrlAccessibility,
        export_shortcodes_to_excel
    )

app_name = 'shortcode'

urlpatterns = [
    path('create/', ShortcodeListeCreateView.as_view(), name='shortcode_list_view'),
    path('update/<pk>/', ShortcodeSingelUpdateView.as_view(), name='shortcode_single_update_view'),
    path('checking/', CheckingUrlAccessibility.as_view(), name='checking_url_accessibility'),
    path('export/', export_shortcodes_to_excel, name='export')
]

shortcode/views/tags_urls.py
from django.urls import path

from shortcode.views.tags_views import (
        CreateTagView,
        get_all_tags,
        TagListView,
        edit_tag,
        TagDeleteView,
    )

app_name = 'tags'

urlpatterns = [
    path('', get_all_tags, name='tags_load'),
    path('create/', CreateTagView.as_view(), name='tags_create'),
    path('list/', TagListView.as_view(), name='tag_list'),
    path('edit/<int:tag_id>/', edit_tag, name='tag_edit'),
    path('delete/<int:tag_id>/', TagDeleteView.as_view(), name='tag_delete'),
]

shortcode/views/tags_views.py
from django.http.response import JsonResponse
from django.utils.translation import gettext_lazy as _
from django.shortcuts import get_object_or_404
from django.views import View

from shortcode.models import Tag

# All User Tags
def get_all_tags(request):
    tags = Tag.objects.filter(user=request.user).values_list('name', flat=True)
    return JsonResponse({'tags': list(tags)})


# Create Tag
class CreateTagView(View):
    def post(self, request, *args, **kwargs):

        tag_name = request.POST.get('tag_name')
        user_id = request.user.id
        
        tag, created = Tag.objects.get_or_create(user_id=user_id, name=tag_name)
        if created:
            return JsonResponse({'message': _(f'Tag "{tag_name}" was created.')}, status=201)
        else:
            return JsonResponse({'message': _(f'Tag "{tag_name}" already exists.')}, status=400)


#View Tags
def get_all_tags(request):
    tags = Tag.objects.filter(user=request.user).values_list('name', flat=True)
    return JsonResponse({'tags': list(tags)})


# Viwe
class TagDeleteView(View):
    def post(self, request, tag_id):
        tag = get_object_or_404(Tag, id=tag_id)
        tag.delete()
        return JsonResponse({'message': _('Tag deleted successfully')})


class TagListView(View):
    def get(self, request):
        tags = Tag.objects.filter(user=request.user)
        data = [{'id': tag.id, 'name': tag.name} for tag in tags]
        return JsonResponse({'tags': data})

# View Tag Edit
def edit_tag(request, tag_id):
    if request.method == 'POST':
        tag = get_object_or_404(Tag, id=tag_id)
        new_tag_name = request.POST.get('tag_name')
  
        tag.name = new_tag_name
        tag.save()

        return JsonResponse({'message': _('Tag updated successfully.')})

shortcode/templates/archive.html
{% extends "basic.html" %}
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static '/assets/css/dashbord.css' %}">
<link rel="stylesheet" type="text/css" href="{% static '/assets/css/archive.css' %}">
{% endblock %}

{% block body %}

    <div id="overlay" data-image="{% static '/gif/load-38_256.gif' %}">
        
    </div>

    <!--Sidebar-->
    {% include "includes/sidebar.html" %}

        <div class="container-fluid p-0 bg-body">

            <!--Navbar-->
            {% include "includes/navbar.html" %}

            <!--Main-->
            <div class="main" id="body-main">

                <div class="container-fluid mt-5 px-4">
                    <div class="row">
                        <div class="col-12">
                            <div class="d-md-flex flex-row align-items-center">
                                <h3 class="p-1" style="margin-top: 10px;">{% trans "Links Archived" %}</h3>
                                <div class="p-1 ms-auto">
                                    <button id="archive-button" class="btn btn-primary mt-1" type="button">{% trans "Unarchive" %}</button>
                                    <button id="delete-button" class="btn btn-danger mt-1" type="button">{% trans "Delete shortcode" %}</button>
                                </div>
                            </div>
                        </div>
                        <!-- <hr> -->
                    </div>
                </div>

                <div class="container-fluid mt-5 px-4">
                    <div class="row">
                        <div class="col-12">
                            <div class="card border-0 shadow-sm">
                            <!--Datatable-->
                            <div id="archived-shortcode-table-container">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th>{% trans "Selection" %}</th>
                                            <th scope="col">{% trans "title" %}</th>
                                            <th scope="col">{% trans "goal" %}</th>
                                            <th scope="col">{% trans "date" %}</th>
                                        </tr>
                                    </thead>
                                    <tbody id="archived-shortcode-table">
                                        <!-- Hier werden die archivierten Shortcodes eingefügt -->
                                    </tbody>
                                </table>
                            </div>


                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>


        <input type="hidden" id="ArchivListLiftView" value="{% url 'archive:achivie_list' %}">
        <input type="hidden" id="ShortcodeUnarchived" value="{% url 'archive:shortcode_unarchived' %}">
    
    
    {% endblock body %}
    
    {% block javasript %}
    <script src="{% static '/js/shortcode.bundle.js' %}"></script>
    {% endblock %}

shortcode/templates/shortcode-view.html
{% extends "basic.html" %}
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static '/assets/css/dashbord.css' %}">
<link rel="stylesheet" type="text/css" href="{% static '/assets/css/analytics.css' %}">
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

<link rel="stylesheet" href="{% static '/css/stylesshort.css' %}">

{% endblock %}

{% block body %}

    <!--Overlay Save-->
    <div id="overlay" data-image="{% static '/gif/load-38_256.gif' %}"></div>
    <div id="overlay-open"></div>

    <!--Sidebar-->
    {% include "includes/sidebar.html" %}

        <div class="container-fluid p-0 bg-body">

            <!--Navbar-->
            {% include "includes/navbar.html" %}

            <!--Main-->
            <div class="main" id="body-main">
                <div class="container-fluid mt-5 px-4">
                    <div class="row">
                        <div class="col-12">
                            <div class="d-flex justify-content-end" id="alertUser">

                            </div>
                        </div>
                        <div class="col-12">
                            <div class="d-md-flex flex-row align-items-center">
                                <h3 class="p-1" style="margin-top: 10px;">Links</h3>
                                <div class="p-1 ms-auto">
                                    <button id="openForm" class="btn btn-primary mt-1" type="button">{% trans "Create link" %}</button>
                                    <button type="button" class="btn btn-primary mt-1" id="exampleModal">{% trans "Create tag" %}</button>
                                    <button id="export-button" class="btn btn-secondary p-2 mt-1" type="button">{% trans "Export shortcodes" %}</button>
                                </div>
                            </div>
                        </div>
                        <!-- <hr> -->
                    </div>
                    <div class="row mt-5">
                        <div class="col-8">
                            <form id="filter-search-form">
                                <div class="row">
                                    <div class="col-12 col-md-3 mt-1">
                                        <select id="tag-filter" class="form-select" aria-label="Default select example">
                                            <!-- <option selected>Open this select menu</option>
                                            <option value="1">One</option> -->
                                        </select>
                                    </div>
                                    <div class="col-12 col-md-3 mt-1">
                                        <input type="text" class="form-control" id="search-input" placeholder='{% trans "Search" %}' name="q">
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
    
                <div class="container-fluid px-4">
                    <div class="row">
                        <div class="col-12 mt-1">
    
                            <!--Data Card-->
                            <div id="gif-load" class="d-none"><img class="mx-auto d-block" src="{% static '/gif/load-38_256.gif' %}" width="50px"></div>
                            <div id="shortcode-list"></div>
                            <div class="d-grid gap-2 col-6 mx-auto">
                                <button id="load-more-button" type="button" class="btn btn-primary mt-3 d-none">{% trans "Load more shortcodes" %}</button>
                            </div>
                            <!--/. Data Card-->
                            
                        </div>
                    </div>
                </div>
            </div>

        </div>

    <!--Crate & Update Form-->
    {% include "includes/form.html" %}
    {% include "includes/modal.html" %}
    {% include "includes/analytics.html" %}

    <input type="hidden" id="ShortcodeSingelUpdateView" value="{% url 'shortcode:shortcode_single_update_view' 0 %}">
    <input type="hidden" id="CheckingUrlAccessibility" value="{% url 'shortcode:checking_url_accessibility' %}">
    <input type="hidden" id="CreateTagView" value="{% url 'tags:tags_create' %}">
    <input type="hidden" id="get_all_tags" value="{% url 'tags:tags_load' %}">
    <input type="hidden" id="TagListView" value="{% url 'tags:tag_list' %}">
    <input type="hidden" id="tag_edit" value="{% url 'tags:tag_edit' 0 %}">
    <input type="hidden" id="tag_delete" value="{% url 'tags:tag_delete' 0 %}">
    <input type="hidden" id="export_shortcodes_to_excel" value="{% url 'shortcode:export' %}">
    <input type="hidden" id="ShortcodeAcivieren" value="{% url 'archive:shortcode_achivie' 0 %}">

{% endblock body %}

{% block javasript %}

<!--Icon Default-->
<input id="favicon-path" type="hidden" value='{% static "/favicon/favicon-32x32.png" %}'>
<script src="{% static '/js/shortcode.bundle.js' %}"></script>

<script>
//var translations = {
//'text1': '{% trans "This is text 1" %}',
//'text2': '{% trans "This is text 2" %}',
//};
//
//$(document).ready(function () {
//var text1 = translations.text1;
//var text2 = translations.text2;
//console.log(text1);
//console.log(text2);
//});
</script>

{% endblock %}